# security_audit.yml
name: Security Audit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Security Audit
        run: python -m security.audit.attack_simulator --strict-mode